### ISSUE TITLE
maintenance_equipment_tags - Description could be more precise

### ISSUE THREAD

**Issue by alexandreduf** [OCA/maintenance#102]
Hi,

I tried this module https://github.com/OCA/maintenance/tree/13.0/maintenance_equipment_tags on runbot and read its description "Adds category tags to equipment".

I still don't understand what this module does.

I noticed a menu called "Equipment tags" where it's possible to create different tags, but I don't see how to put a tag on an equipment and how it would be useful. Also, the module says "category tags", but it looks like it's more "Equipment tags".

Could anybody help here? I will then propose a more detailed description of the module once I understand its use.

Thanks for your great work!

**Comment by dalonsod** [comment]
Hello,

maybe you've found a bug, or an incompatibility between this addon and other one for v13.

If you go to an equipment form, set Odoo in debug mode and inspect Fields view get debug menu, you'll see the equipment tags placeholder, that doesn't seem to work:

![imagen](https://user-images.githubusercontent.com/12749832/91823380-692bf180-ec39-11ea-98c5-3696108b34a6.png)

@jarroyomorales could you check?

**Comment by jarroyomorales** [comment]
Hi @dalonsod @alexandreduf ! I just tested it and it is working fine for me 

![image](https://user-images.githubusercontent.com/47532076/93195456-91dbdd00-f749-11ea-8b78-257d6530bc85.png)

And about the description maybe I could change it for `Adds grouping tags to equipments` ?

**Comment by dalonsod** [comment]
> Hi @dalonsod @alexandreduf ! I just tested it and it is working fine for me

It's weird, when I tested two weeks ago I wasn't able to access tags within the form... Now it works 😅

**Comment by etobella** [comment]
As it seems solved, I will proceed closing the issue
