### ISSUE TITLE
maintenance_equipment_status - Can't set a status to an equipment

### ISSUE THREAD

**Issue by alexandreduf** [OCA/maintenance#103]
Hi,

I tried the following module : https://github.com/OCA/maintenance/tree/13.0/maintenance_equipment_status

I can manage to create statuses in Maintenance>Configuration>Equipment Statuses and can decide which equipment categories will have those statuses.

Then, at the top right corner of the Equipment form view, I can see a ribbon that displays the different statuses that an equipment from a category can have.

![Buttons not clickable](https://user-images.githubusercontent.com/70237796/92983359-eee94180-f470-11ea-8b7e-4c6e9df80fe5.png)

Problem : the buttons in the ribbon are not clickable (I guess they are supposed to be clickable just as they usually are elsewhere in Odoo). I can’t select a status from that upper ribbon. And I can’t seem to find anywhere a button or a field that allows me to set a status.

Is it me or this is a bug?

Thank you for your great work! I'm eager to try that module once I figure that out!

**Comment by dalonsod** [comment]
Hello,

Tested on runbot, making this change on https://github.com/OCA/maintenance/blob/13.0/maintenance_equipment_status/views/maintenance_equipment_views.xml#L13 the status bar becomes clickable:
```
options="{'clickable': '1'}"
```

Maybe you could locally test and make a PR to fix it

**Comment by dalonsod** [comment]
Hi @alexandreduf , did you take a look at this?

**Comment by etobella** [comment]
@alexandreduf Will you make the PR or do you need some help?

**Comment by alexandreduf** [comment]
@dalonsod 
@etobella 

Hi,

Sorry for the delay, I was away for a bit.
I'm not familiar with coding, so if @etobella can check @dalonsod's suggestion and do the PR, that would be great!

Thank you guys!

**Comment by dalonsod** [comment]
@etobella this issue can be closed
