### ISSUE TITLE
[IMP] maintenance_sequence: code, partner_ref and serial_no

### ISSUE THREAD

**Issue by etobella** [OCA/maintenance#159]
Reviewing odoo code and OCA code I found that fields `code` and `serial_no` should fulfill the same logic. 

Serial number is a field that should be used to add our internal serial number, as it is unique in our database. On the other side, partner_ref should be used to write the serial number of the vendor/manufacturer. Both fields are searchable using `name`:

https://github.com/odoo/odoo/blob/master/addons/maintenance/views/maintenance_views.xml#L507-L509

So, code and serial_no are internal identifier. I think the sequence should fulfill serial_no. The biggest problem is how to manage the migration, as it could be complicated to manage (Maybe on the migration from 14 to 15?)

WDYT?

@dalonsod @LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
That makes total sense, thanks for the heads-ups. For me it could even be possible to propose the change in v14 and even v13 if migration scripts are provided.

My 2 cents.

**Comment by dalonsod** [comment]
@etobella inspecting the code I've found that `code` isn't actually unique, so you can assign the same `code` to more than one equipment. I think it's an issue rather than a feature... then, if a migration script e.g. should move current codes to `serial_no`, when codes are filled and serial numbers not, an error could happen.

**Comment by etobella** [comment]
Yes, it is not unique, but it will probably be unless you make the sequence wrongly

**Comment by etobella** [comment]
Also, that's the work of a great migration script :wink:

**Comment by dalonsod** [comment]
> 
> 
> Yes, it is not unique, but it will probably be unless you make the sequence wrongly

Or you manually fill the same `code` twice, bypassing sequence automation.
