### ISSUE TITLE
maintenance_plan: a clarification on the position of function 'get_relativedelta'

### ISSUE THREAD

**Issue by mymage** [OCA/maintenance#182]
Hi, I'm doing some work around maintenance and I have the necessity to hinerit the 'get_relativedelta' function.
I need to use the original one (as with super()) or doing something else (eg based on the value of step).
But because it is a function and not a method of a class, I think that it is not possible.
So, if I'm right, what do you think to move get_relativedelta inside the MaintenancePlan class?

PS. I did what I need with another way but if it is possible I would prefer to hinerit the get_relativedelta function.

**Comment by etobella** [comment]
Sure! Propose a PR so we can merge it

**Comment by mymage** [comment]
Ok I can do it. Do you think it is better to wait someone else comment?

**Comment by etobella** [comment]
We can wait if you prefer. But, IMO it is better to propose a PR if it is easy and discuss it in the PR.

**Comment by mymage** [comment]
Open #183
