### ISSUE TITLE
[14.0] maintenance_equipment_status: The license LGPL-3 conflicts with one of its dependencies.

### ISSUE THREAD

**Issue by dreispt** [OCA/maintenance#192]
Error on the Odoo App store:

> maintenance_equipment_status: The license LGPL-3 conflicts with one of its dependencies. Please make sure that you comply with the licenses compatibility. See our FAQ at https://apps.odoo.com/apps/faq#maintainer_faq_04 .

**Comment by dalonsod** [comment]
Hello, 

`maintenance_equipment_status` depends on `base_maintenance` since v12, and this addon is currently `AGPL-3`, I think that's the problem. @ForgeFlow would you consider changing `maintenance_equipment_status` license to `AGPL-3`?

**Comment by etobella** [comment]
You can check on https://github.com/OCA/maintenance/pull/154 that there is no problem with the relicense. You can propose a PR if you wish.

**Comment by dreispt** [comment]
@etobella That PR was not merged. The `base_maintenance` module still displays AGPL License:
https://github.com/OCA/maintenance/blob/14.0/base_maintenance/__manifest__.py#L11

**Comment by dreispt** [comment]
![image](https://user-images.githubusercontent.com/1246629/143900797-584aae1d-b813-4d60-8386-4978665a287a.png)

**Comment by etobella** [comment]
Yes, the PR that fixes all is here:
#157 as soon as it is green, I will merge it
