### ISSUE TITLE
[14.0] maintenance_plan: improvable UI design

### ISSUE THREAD

**Issue by pedrocs-exo** [OCA/maintenance#206]
The maintenance plan tree view inside the equipment form could use shorter labels. This would make it easier for the user to read and also prevent overlapping the form boundaries.

I'll soon make a PR for turning this:
![image](https://user-images.githubusercontent.com/8116385/149324671-f20a773f-ef6f-48a7-9f24-09989d9431dc.png)

into this:
![image](https://user-images.githubusercontent.com/8116385/149324712-bfdfbcca-9763-49d1-80b0-4f7b4ef583cc.png)

**Comment by athifbinu** [comment]
hello to improve the project ui and style and in css
