### ISSUE TITLE
[V14] maintenance_account, dont create same equipment category of every single unit when tracking by serial on the product with asset profile ticked

### ISSUE THREAD

**Issue by bunhin** [OCA/maintenance#229]
**Is your feature request related to a problem?**
It is not causing an error now, but I consider as a bug and may need improvement,

The current behavior is creating the same equipment category when validating vendor bills for "can be maintained item" when the item is tracked by serial and the purchase qty more than 1, in combination with creating the assets (an asset profile is selected)

Step to reproduce:
0. Install The OCA asset management module, and create an asset profile
1. install maintenance_product and maintenance_account module
2. Create a product category  for example Laptop
3. Create a laptop item with category = Laptop,  then check  "Can Be Maintained" on product form and use tracking with serial.
4. Create purchase for laptop item with 10 units in quantity, confirm the PO
5. Receive product and enter or generate serial number for 10 items
6. Validate the receive
7. Create the vendor bill, indicate the bill date,  and select the asset profile created above, doing so the bill line become 10 lines now (correct behavior)
8. confirm the bill.
9. It will create 10 equipment items with 10 equipment categories  (1 equipment category for 1 laptop item) with the same name of the equipment category (Laptop)

Expected behavior --> only 1 equipment category should be created (Laptop) and all the 10 units of laptop items in the same equipment category.

**Comment by pedrobaeza** [comment]
Thanks for the report. You can contribute with the fix via a pull request.

**Comment by bunhin** [comment]
Overall all modules are excellent features that make the maintenance app usable. I  do highly appreciate it.

**Comment by etobella** [comment]
@pedrobaeza I was checking, Why do you need to create the category? I mean, it is not a required field :thinking:
