### ISSUE TITLE
Maintenance Notes Field

### ISSUE THREAD

**Issue by ljacobo** [OCA/maintenance#26]
Hi,

im trying to make a new field in the maintenance.kind model named "notes", to be able to have a detail of tasks of a specific maintenance kind.

there is a way to related this field with another field in the maintenance.request in order to autofill those notes when the preventive maintenance is generated? in the same way like the maintenance_kind_id.

thanks.

**Comment by etobella** [comment]
You should need to inherit the _prepare_request_from_plan function and add it to the created request. Similar to maintenance_project_plan from 12.0
