### ISSUE TITLE
Cloning this repository gives "nonexistent ref" error

### ISSUE THREAD

**Issue by yvaucher** [OCA/maintenance#3]
git clone of this repo gives:
warning: remote HEAD refers to non-existent ref, unable to checkout.

Seems something is wrong with the default branch.

Whereas it is still possible to do a `git checkout 10.0` afterward this error makes trouble with submodules.

@pedrobaeza Could you try to set again the default branch? (maybe creating a dummy branch set it as default and then set 10.0 as the default again)

**Comment by pedrobaeza** [comment]
Strange, but I have fixed it the way you have told me. Thanks for noticing.

**Comment by grindtildeath** [comment]
@pedrobaeza I also had a issue doing a git submodule add in one of our projects :

```
┌─[ajuillerat@wrk69~/PycharmProjects/customer/customer_odoo]
└─> git submodule add git@github.com:OCA/maintenance.git odoo/external-src/maintenance
Clonage dans 'odoo/external-src/maintenance'...
remote: Counting objects: 16, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 16 (delta 3), reused 15 (delta 2), pack-reused 0
Réception d'objets: 100% (16/16), 14.25 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (3/3), fait.
Vérification de la connectivité... fait.
fatal: Vous êtes sur une branche qui doit encore naître
Impossible d'extraire le sous-module 'odoo/external-src/maintenance'
```

Message in french say :
fatal: you are on a branch yet to be born

I still could create a branch afterwards without issue, but I miss the entry in .gitmodules

**Comment by pedrobaeza** [comment]
But have you tried again after what I have done?

**Comment by yvaucher** [comment]
@pedrobaeza Thanks. It worked I don't have the error anymore

**Comment by grindtildeath** [comment]
@pedrobaeza I didn't, but now it's ok. Thanks for fixing.
