### ISSUE TITLE
Wrong filed attribute is generating error.

### ISSUE THREAD

**Issue by peterromao** [OCA/maintenance#329]
https://github.com/OCA/maintenance/blob/91ebb88f97b30adf4c4f527d698d9b3986e7db68/maintenance_product/models/maintenance_equipment.py#L29

This line should be:

self.partner_id = first_seller.partner_id

instead of self.partner_id = first_seller.name

**Comment by pedrobaeza** [comment]
You are not indicating Odoo version, but please do the PR amending the problem.

**Comment by peterromao** [comment]
Hello Pedro,

I am sorry about the lack of information on the version. I was in a hurry to dinner. :-)

Version is odoo 16 CE.

The code was throwing an error and I tracked it down to that line. My change seems to have done the trick.

P.S. what does do the PR mean? I am fairly new to this github thing.

**Comment by pedrobaeza** [comment]
PR = Pull Request, that is to contribute here with the patch.

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst
