### ISSUE TITLE
Label could improve

### ISSUE THREAD

**Issue by peterromao** [OCA/maintenance#330]
https://github.com/OCA/maintenance/blob/3c30fc1a3160538f2d690e7195b29be81c4e572c/maintenance_product/models/product_template.py#L9

Hello,

Not withstanding the effort put into this module, which I applaud, I would kindly suggest changing the Label string of the maintenance_ok field to either:

"Can be Maintained"

or

"Can have Maintenance"

PS. I have a pt.po file that you might like to have attached to the i18n directory. To whom should I send this?

**Comment by dalonsod** [comment]
Hello @peterromao you can contribute to PT translation tasks using OCA weblate (see https://odoo-community.org/resources/translate)
