### ISSUE TITLE
maintenance_plan: next_maintenance_date should be stored=True

### ISSUE THREAD

**Issue by dalonsod** [OCA/maintenance#34]
Hi,

the current `next_maintenance_date` is defined as a computed, non-stored field. The compute method (`_compute_next_maintenance`) has an `api.depends` decorator, but compute method is always executed, because the field hasn't the store attribute set to `True`. I think it's incorrect.

One consequence of this issue is a very slow performance in request generations via cron (method `_cron_generate_requests`), since `next_maintenance_date` value is needed when creating the requests. I've tested that method with more than 1,000 requests to be created: with the current definition it takes more than half an hour (actually I stopped execution); with `store=True` it took only about two minutes.

If my analysis is correct, I can make a PR to change this.

**Comment by dalonsod** [comment]
@astirpe @pedrobaeza what do you think about this?

**Comment by astirpe** [comment]
@dalonsod your analysis is correct. Making the field `store=True` is okay. :+1: 

In addition to `store=True`, you may also want to consider to set `next_maintenance_date` field `readonly=False`. This way the `next_maintenance_date` can be manually modified. It's a functional change, not sure if it fits your needs, but it would be opening new possibilities for the end user.

**Comment by pedrobaeza** [comment]
Sorry, I'm not using these modules. I only did your initial kick-off in OCA / this project :wink:

**Comment by dalonsod** [comment]
> @dalonsod your analysis is correct. Making the field store=True is okay. 👍

Thanks, I'll make a PR as soon as possible.

> In addition to `store=True`, you may also want to consider to set `next_maintenance_date` field `readonly=False`. This way the `next_maintenance_date` can be manually modified. It's a functional change, not sure if it fits your needs, but it would be opening new possibilities for the end user.

It's an interesing feature, but I don't need it right now. Anyway, I should be interested later. What do you think, should it be another module, or a change inside `maintenance_plan`?

**Comment by dalonsod** [comment]
> 
> 
> Sorry, I'm not using these modules. I only did your initial kick-off in OCA / this project 😉

OK, I'll keep it in mind, thanks anyway.

**Comment by astirpe** [comment]
> It's an interesing feature, but I don't need it right now. Anyway, I should be interested later. What do you think, should it be another module, or a change inside maintenance_plan?

Just inside `maintenance_plan`, you can do it within the same PR. I'm sure it will not have any unwanted impacts on your projects.

**Comment by dalonsod** [comment]
Well, I made the change locally and found the following problem: when debugging and editing a plan (only the `next_maintenance_date` field), the `_compute_next_maintenance` is always fired (I don't know why) and, consequently, the recently changed `next_maintenance_date` value can be ignored and overriden (for example, when I change the previously calculated date by a later one).

Is desiredable this behavior?

**Comment by astirpe** [comment]
@dalonsod I'm not sure I'm getting your point.

Let's proceed like this: open your PR with the `stored=True` only and I will immediately approve it.

We will discuss about the other things in a separate PR.

**Comment by dalonsod** [comment]
@astirpe as soon as #35 is merged I'll open another one with the `readonly=False`. Then, I'll try to explain better the related issue.

**Comment by etobella** [comment]
Closing, as the PR has already been merged
