### ISSUE TITLE
Change license of maintenance_location to LGPL

### ISSUE THREAD

**Issue by AnizR** [OCA/maintenance#394]
Hi,

Maintenance_location is currentry AGPL.

I am currently working on an enterprise module and I would like to introduce the notion of maintenance.location in this one.
More precisely, I work on the link between mrp and maintenance (module: mrp_maintenance).

A module with a "enterprise" or "other proprietary" license can't depend on a module with a AGPL License. 

Would you agree to change its license to LGPL?

As authors and contributors, do you have any objection to that @etobella @kluna1998 @olgamarcocb @IT-Ideas ?

**Comment by etobella** [comment]
No, I don't feel comfortable with a change of the license, if you want to use it, you can provide the code to OCA :wink:

**Comment by AnizR** [comment]
Okay, I understand. I will close this MR
I found a workaround to not use the enterprise module.
My module is not "generic" enough to be pushed to OCA imo.

But I contribute as much as possible to OCA :smile:
