### ISSUE TITLE
[IMP] maintenance_project: add reference on form

### ISSUE THREAD

**Issue by mymage** [OCA/maintenance#421]
This is a reminder for an improvement.
I think it will be better to have [in the Project form the reference to the equipment (if present) ALREADY PRESENT] and in the Equipment form the reference to the Project.

**Comment by dalonsod** [comment]
Hello @mymage one of the features you'vre requested is already available, yo can check at runboat (example brought by #401 ):

**Project Form**

![imagen](https://github.com/user-attachments/assets/c1d52251-e39a-467d-bff2-a0c8faa0cfb8)


Regarding to equipment form and project visibility, I've checked and it's also covered, if equipment is created with "Create Project From Equipment" checked during creation, you can check at v16 runboat. But it doesn't seem to work for v17 migration PR, we'll check it

**Comment by mymage** [comment]
@dalonsod I tested it on Runboat but I didn't pay attention to the button at the top, I was looking for a field in the form. 
I changed de issue.

**Comment by dalonsod** [comment]
> and in the Equipment form the reference to the Project.

Covered too in v17 migration at #401 , there was a bug and it's now fixed, so this issue could be closed IMO
